/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGD

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* Contract support. */
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_DSetPendingException(SWIG_DException, msg); return nullreturn; } else


// Support for throwing D exceptions from C/C++.
typedef enum {
  SWIG_DException = 0,
  SWIG_DIllegalArgumentException,
  SWIG_DIllegalElementException,
  SWIG_DIOException,
  SWIG_DNoSuchElementException,
} SWIG_DExceptionCodes;

typedef void (* SWIG_DExceptionCallback_t)(const char *);

typedef struct {
  SWIG_DExceptionCodes code;
  SWIG_DExceptionCallback_t callback;
} SWIG_DException_t;

static SWIG_DException_t SWIG_d_exceptions[] = {
  { SWIG_DException, NULL },
  { SWIG_DIllegalArgumentException, NULL },
  { SWIG_DIllegalElementException, NULL },
  { SWIG_DIOException, NULL },
  { SWIG_DNoSuchElementException, NULL }
};

static void SWIGUNUSED SWIG_DSetPendingException(SWIG_DExceptionCodes code, const char *msg) {
  if ((size_t)code < sizeof(SWIG_d_exceptions)/sizeof(SWIG_DException_t)) {
    SWIG_d_exceptions[code].callback(msg);
  } else {
    SWIG_d_exceptions[SWIG_DException].callback(msg);
  }
}

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterExceptionCallbacks_ovr(
  SWIG_DExceptionCallback_t exceptionCallback,
  SWIG_DExceptionCallback_t illegalArgumentCallback,
  SWIG_DExceptionCallback_t illegalElementCallback,
  SWIG_DExceptionCallback_t ioCallback,
  SWIG_DExceptionCallback_t noSuchElementCallback) {
  SWIG_d_exceptions[SWIG_DException].callback = exceptionCallback;
  SWIG_d_exceptions[SWIG_DIllegalArgumentException].callback = illegalArgumentCallback;
  SWIG_d_exceptions[SWIG_DIllegalElementException].callback = illegalElementCallback;
  SWIG_d_exceptions[SWIG_DIOException].callback = ioCallback;
  SWIG_d_exceptions[SWIG_DNoSuchElementException].callback = noSuchElementCallback;
}


// Callback for returning strings to D without leaking memory.
typedef char * (* SWIG_DStringHelperCallback)(const char *);
static SWIG_DStringHelperCallback SWIG_d_string_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterStringCallback_ovr(SWIG_DStringHelperCallback callback) {
  SWIG_d_string_callback = callback;
}


#include "OVR_CAPI.h"
#include "OVR_CAPI_GL.h"

using namespace OVR;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void D_ovrVector2i_x_set(void * jarg1, int jarg2) {
  struct ovrVector2i_ *arg1 = (struct ovrVector2i_ *) 0 ;
  int arg2 ;
  
  arg1 = (struct ovrVector2i_ *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT int D_ovrVector2i_x_get(void * jarg1) {
  int jresult ;
  struct ovrVector2i_ *arg1 = (struct ovrVector2i_ *) 0 ;
  int result;
  
  arg1 = (struct ovrVector2i_ *)jarg1;
  result = (int) ((arg1)->x);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrVector2i_y_set(void * jarg1, int jarg2) {
  struct ovrVector2i_ *arg1 = (struct ovrVector2i_ *) 0 ;
  int arg2 ;
  
  arg1 = (struct ovrVector2i_ *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT int D_ovrVector2i_y_get(void * jarg1) {
  int jresult ;
  struct ovrVector2i_ *arg1 = (struct ovrVector2i_ *) 0 ;
  int result;
  
  arg1 = (struct ovrVector2i_ *)jarg1;
  result = (int) ((arg1)->y);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrVector2i() {
  void * jresult ;
  struct ovrVector2i_ *result = 0 ;
  
  result = (struct ovrVector2i_ *)calloc(1, sizeof(struct ovrVector2i_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrVector2i(void * jarg1) {
  struct ovrVector2i_ *arg1 = (struct ovrVector2i_ *) 0 ;
  
  arg1 = (struct ovrVector2i_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrSizei_w_set(void * jarg1, int jarg2) {
  struct ovrSizei_ *arg1 = (struct ovrSizei_ *) 0 ;
  int arg2 ;
  
  arg1 = (struct ovrSizei_ *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->w = arg2;
}


SWIGEXPORT int D_ovrSizei_w_get(void * jarg1) {
  int jresult ;
  struct ovrSizei_ *arg1 = (struct ovrSizei_ *) 0 ;
  int result;
  
  arg1 = (struct ovrSizei_ *)jarg1;
  result = (int) ((arg1)->w);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrSizei_h_set(void * jarg1, int jarg2) {
  struct ovrSizei_ *arg1 = (struct ovrSizei_ *) 0 ;
  int arg2 ;
  
  arg1 = (struct ovrSizei_ *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->h = arg2;
}


SWIGEXPORT int D_ovrSizei_h_get(void * jarg1) {
  int jresult ;
  struct ovrSizei_ *arg1 = (struct ovrSizei_ *) 0 ;
  int result;
  
  arg1 = (struct ovrSizei_ *)jarg1;
  result = (int) ((arg1)->h);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrSizei() {
  void * jresult ;
  struct ovrSizei_ *result = 0 ;
  
  result = (struct ovrSizei_ *)calloc(1, sizeof(struct ovrSizei_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrSizei(void * jarg1) {
  struct ovrSizei_ *arg1 = (struct ovrSizei_ *) 0 ;
  
  arg1 = (struct ovrSizei_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrRecti_Pos_set(void * jarg1, void * jarg2) {
  struct ovrRecti_ *arg1 = (struct ovrRecti_ *) 0 ;
  ovrVector2i *arg2 = (ovrVector2i *) 0 ;
  
  arg1 = (struct ovrRecti_ *)jarg1;
  arg2 = (ovrVector2i *)jarg2;
  if (arg1) (arg1)->Pos = *arg2;
}


SWIGEXPORT void * D_ovrRecti_Pos_get(void * jarg1) {
  void * jresult ;
  struct ovrRecti_ *arg1 = (struct ovrRecti_ *) 0 ;
  ovrVector2i *result = 0 ;
  
  arg1 = (struct ovrRecti_ *)jarg1;
  result = (ovrVector2i *)& ((arg1)->Pos);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrRecti_Size_set(void * jarg1, void * jarg2) {
  struct ovrRecti_ *arg1 = (struct ovrRecti_ *) 0 ;
  ovrSizei *arg2 = (ovrSizei *) 0 ;
  
  arg1 = (struct ovrRecti_ *)jarg1;
  arg2 = (ovrSizei *)jarg2;
  if (arg1) (arg1)->Size = *arg2;
}


SWIGEXPORT void * D_ovrRecti_Size_get(void * jarg1) {
  void * jresult ;
  struct ovrRecti_ *arg1 = (struct ovrRecti_ *) 0 ;
  ovrSizei *result = 0 ;
  
  arg1 = (struct ovrRecti_ *)jarg1;
  result = (ovrSizei *)& ((arg1)->Size);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrRecti() {
  void * jresult ;
  struct ovrRecti_ *result = 0 ;
  
  result = (struct ovrRecti_ *)calloc(1, sizeof(struct ovrRecti_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrRecti(void * jarg1) {
  struct ovrRecti_ *arg1 = (struct ovrRecti_ *) 0 ;
  
  arg1 = (struct ovrRecti_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrQuatf_x_set(void * jarg1, float jarg2) {
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float D_ovrQuatf_x_get(void * jarg1) {
  float jresult ;
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float result;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  result = (float) ((arg1)->x);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrQuatf_y_set(void * jarg1, float jarg2) {
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float D_ovrQuatf_y_get(void * jarg1) {
  float jresult ;
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float result;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  result = (float) ((arg1)->y);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrQuatf_z_set(void * jarg1, float jarg2) {
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT float D_ovrQuatf_z_get(void * jarg1) {
  float jresult ;
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float result;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  result = (float) ((arg1)->z);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrQuatf_w_set(void * jarg1, float jarg2) {
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->w = arg2;
}


SWIGEXPORT float D_ovrQuatf_w_get(void * jarg1) {
  float jresult ;
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  float result;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  result = (float) ((arg1)->w);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrQuatf() {
  void * jresult ;
  struct ovrQuatf_ *result = 0 ;
  
  result = (struct ovrQuatf_ *)calloc(1, sizeof(struct ovrQuatf_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrQuatf(void * jarg1) {
  struct ovrQuatf_ *arg1 = (struct ovrQuatf_ *) 0 ;
  
  arg1 = (struct ovrQuatf_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrVector2f_x_set(void * jarg1, float jarg2) {
  struct ovrVector2f_ *arg1 = (struct ovrVector2f_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrVector2f_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float D_ovrVector2f_x_get(void * jarg1) {
  float jresult ;
  struct ovrVector2f_ *arg1 = (struct ovrVector2f_ *) 0 ;
  float result;
  
  arg1 = (struct ovrVector2f_ *)jarg1;
  result = (float) ((arg1)->x);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrVector2f_y_set(void * jarg1, float jarg2) {
  struct ovrVector2f_ *arg1 = (struct ovrVector2f_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrVector2f_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float D_ovrVector2f_y_get(void * jarg1) {
  float jresult ;
  struct ovrVector2f_ *arg1 = (struct ovrVector2f_ *) 0 ;
  float result;
  
  arg1 = (struct ovrVector2f_ *)jarg1;
  result = (float) ((arg1)->y);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrVector2f() {
  void * jresult ;
  struct ovrVector2f_ *result = 0 ;
  
  result = (struct ovrVector2f_ *)calloc(1, sizeof(struct ovrVector2f_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrVector2f(void * jarg1) {
  struct ovrVector2f_ *arg1 = (struct ovrVector2f_ *) 0 ;
  
  arg1 = (struct ovrVector2f_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrVector3f_x_set(void * jarg1, float jarg2) {
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float D_ovrVector3f_x_get(void * jarg1) {
  float jresult ;
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float result;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  result = (float) ((arg1)->x);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrVector3f_y_set(void * jarg1, float jarg2) {
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float D_ovrVector3f_y_get(void * jarg1) {
  float jresult ;
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float result;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  result = (float) ((arg1)->y);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrVector3f_z_set(void * jarg1, float jarg2) {
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT float D_ovrVector3f_z_get(void * jarg1) {
  float jresult ;
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  float result;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  result = (float) ((arg1)->z);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrVector3f() {
  void * jresult ;
  struct ovrVector3f_ *result = 0 ;
  
  result = (struct ovrVector3f_ *)calloc(1, sizeof(struct ovrVector3f_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrVector3f(void * jarg1) {
  struct ovrVector3f_ *arg1 = (struct ovrVector3f_ *) 0 ;
  
  arg1 = (struct ovrVector3f_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrMatrix4f_M_set(void * jarg1, void * jarg2) {
  struct ovrMatrix4f_ *arg1 = (struct ovrMatrix4f_ *) 0 ;
  float (*arg2)[4] ;
  
  arg1 = (struct ovrMatrix4f_ *)jarg1;
  arg2 = (float (*)[4])jarg2; 
  {
    float (*inp)[4] = (float (*)[4])(arg2);
    float (*dest)[4] = (float (*)[4])(arg1->M);
    size_t ii = 0;
    for (; ii < 4; ++ii) {
      float *ip = inp[ii];
      float *dp = dest[ii];
      size_t jj = 0;
      for (; jj < 4; ++jj) dp[jj] = ip[jj];
    }
  }
}


SWIGEXPORT void * D_ovrMatrix4f_M_get(void * jarg1) {
  void * jresult ;
  struct ovrMatrix4f_ *arg1 = (struct ovrMatrix4f_ *) 0 ;
  float (*result)[4] = 0 ;
  
  arg1 = (struct ovrMatrix4f_ *)jarg1;
  result = (float (*)[4])(float (*)[4]) ((arg1)->M);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * D_new_ovrMatrix4f() {
  void * jresult ;
  struct ovrMatrix4f_ *result = 0 ;
  
  result = (struct ovrMatrix4f_ *)calloc(1, sizeof(struct ovrMatrix4f_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrMatrix4f(void * jarg1) {
  struct ovrMatrix4f_ *arg1 = (struct ovrMatrix4f_ *) 0 ;
  
  arg1 = (struct ovrMatrix4f_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrPosef_Orientation_set(void * jarg1, void * jarg2) {
  struct ovrPosef_ *arg1 = (struct ovrPosef_ *) 0 ;
  ovrQuatf *arg2 = (ovrQuatf *) 0 ;
  
  arg1 = (struct ovrPosef_ *)jarg1;
  arg2 = (ovrQuatf *)jarg2;
  if (arg1) (arg1)->Orientation = *arg2;
}


SWIGEXPORT void * D_ovrPosef_Orientation_get(void * jarg1) {
  void * jresult ;
  struct ovrPosef_ *arg1 = (struct ovrPosef_ *) 0 ;
  ovrQuatf *result = 0 ;
  
  arg1 = (struct ovrPosef_ *)jarg1;
  result = (ovrQuatf *)& ((arg1)->Orientation);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPosef_Position_set(void * jarg1, void * jarg2) {
  struct ovrPosef_ *arg1 = (struct ovrPosef_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrPosef_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->Position = *arg2;
}


SWIGEXPORT void * D_ovrPosef_Position_get(void * jarg1) {
  void * jresult ;
  struct ovrPosef_ *arg1 = (struct ovrPosef_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrPosef_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->Position);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrPosef() {
  void * jresult ;
  struct ovrPosef_ *result = 0 ;
  
  result = (struct ovrPosef_ *)calloc(1, sizeof(struct ovrPosef_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrPosef(void * jarg1) {
  struct ovrPosef_ *arg1 = (struct ovrPosef_ *) 0 ;
  
  arg1 = (struct ovrPosef_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrPoseStatef_Pose_set(void * jarg1, void * jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrPosef *arg2 = (ovrPosef *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (ovrPosef *)jarg2;
  if (arg1) (arg1)->Pose = *arg2;
}


SWIGEXPORT void * D_ovrPoseStatef_Pose_get(void * jarg1) {
  void * jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrPosef *result = 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (ovrPosef *)& ((arg1)->Pose);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPoseStatef_AngularVelocity_set(void * jarg1, void * jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->AngularVelocity = *arg2;
}


SWIGEXPORT void * D_ovrPoseStatef_AngularVelocity_get(void * jarg1) {
  void * jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->AngularVelocity);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPoseStatef_LinearVelocity_set(void * jarg1, void * jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->LinearVelocity = *arg2;
}


SWIGEXPORT void * D_ovrPoseStatef_LinearVelocity_get(void * jarg1) {
  void * jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->LinearVelocity);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPoseStatef_AngularAcceleration_set(void * jarg1, void * jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->AngularAcceleration = *arg2;
}


SWIGEXPORT void * D_ovrPoseStatef_AngularAcceleration_get(void * jarg1) {
  void * jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->AngularAcceleration);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPoseStatef_LinearAcceleration_set(void * jarg1, void * jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->LinearAcceleration = *arg2;
}


SWIGEXPORT void * D_ovrPoseStatef_LinearAcceleration_get(void * jarg1) {
  void * jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->LinearAcceleration);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrPoseStatef_TimeInSeconds_set(void * jarg1, double jarg2) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  double arg2 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  arg2 = (double)jarg2;
  if (arg1) (arg1)->TimeInSeconds = arg2;
}


SWIGEXPORT double D_ovrPoseStatef_TimeInSeconds_get(void * jarg1) {
  double jresult ;
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  double result;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  result = (double) ((arg1)->TimeInSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrPoseStatef() {
  void * jresult ;
  struct ovrPoseStatef_ *result = 0 ;
  
  result = (struct ovrPoseStatef_ *)calloc(1, sizeof(struct ovrPoseStatef_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrPoseStatef(void * jarg1) {
  struct ovrPoseStatef_ *arg1 = (struct ovrPoseStatef_ *) 0 ;
  
  arg1 = (struct ovrPoseStatef_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrFovPort_UpTan_set(void * jarg1, float jarg2) {
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->UpTan = arg2;
}


SWIGEXPORT float D_ovrFovPort_UpTan_get(void * jarg1) {
  float jresult ;
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float result;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  result = (float) ((arg1)->UpTan);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFovPort_DownTan_set(void * jarg1, float jarg2) {
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->DownTan = arg2;
}


SWIGEXPORT float D_ovrFovPort_DownTan_get(void * jarg1) {
  float jresult ;
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float result;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  result = (float) ((arg1)->DownTan);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFovPort_LeftTan_set(void * jarg1, float jarg2) {
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->LeftTan = arg2;
}


SWIGEXPORT float D_ovrFovPort_LeftTan_get(void * jarg1) {
  float jresult ;
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float result;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  result = (float) ((arg1)->LeftTan);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFovPort_RightTan_set(void * jarg1, float jarg2) {
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->RightTan = arg2;
}


SWIGEXPORT float D_ovrFovPort_RightTan_get(void * jarg1) {
  float jresult ;
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  float result;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  result = (float) ((arg1)->RightTan);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrFovPort() {
  void * jresult ;
  struct ovrFovPort_ *result = 0 ;
  
  result = (struct ovrFovPort_ *)calloc(1, sizeof(struct ovrFovPort_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrFovPort(void * jarg1) {
  struct ovrFovPort_ *arg1 = (struct ovrFovPort_ *) 0 ;
  
  arg1 = (struct ovrFovPort_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrHmdDesc_Handle_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrHmd arg2 = (ovrHmd) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrHmd)jarg2;
  if (arg1) (arg1)->Handle = arg2;
}


SWIGEXPORT void * D_ovrHmdDesc_Handle_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrHmd result;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrHmd) ((arg1)->Handle);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_Type_set(void * jarg1, int jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrHmdType arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrHmdType)jarg2; 
  if (arg1) (arg1)->Type = arg2;
}


SWIGEXPORT int D_ovrHmdDesc_Type_get(void * jarg1) {
  int jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrHmdType result;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrHmdType) ((arg1)->Type);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_ProductName_set(void * jarg1, char * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->ProductName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->ProductName, (const char *)arg2);
    } else {
      arg1->ProductName = 0;
    }
  }
}


SWIGEXPORT char * D_ovrHmdDesc_ProductName_get(void * jarg1) {
  char * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (char *) ((arg1)->ProductName);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_Manufacturer_set(void * jarg1, char * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->Manufacturer = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->Manufacturer, (const char *)arg2);
    } else {
      arg1->Manufacturer = 0;
    }
  }
}


SWIGEXPORT char * D_ovrHmdDesc_Manufacturer_get(void * jarg1) {
  char * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (char *) ((arg1)->Manufacturer);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_Caps_set(void * jarg1, unsigned int jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->Caps = arg2;
}


SWIGEXPORT unsigned int D_ovrHmdDesc_Caps_get(void * jarg1) {
  unsigned int jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  unsigned int result;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (unsigned int) ((arg1)->Caps);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_DistortionCaps_set(void * jarg1, unsigned int jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->DistortionCaps = arg2;
}


SWIGEXPORT unsigned int D_ovrHmdDesc_DistortionCaps_get(void * jarg1) {
  unsigned int jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  unsigned int result;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (unsigned int) ((arg1)->DistortionCaps);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_Resolution_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrSizei *arg2 = (ovrSizei *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrSizei *)jarg2;
  if (arg1) (arg1)->Resolution = *arg2;
}


SWIGEXPORT void * D_ovrHmdDesc_Resolution_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrSizei *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrSizei *)& ((arg1)->Resolution);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_WindowsPos_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrVector2i *arg2 = (ovrVector2i *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrVector2i *)jarg2;
  if (arg1) (arg1)->WindowsPos = *arg2;
}


SWIGEXPORT void * D_ovrHmdDesc_WindowsPos_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrVector2i *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrVector2i *)& ((arg1)->WindowsPos);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_DefaultEyeFov_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrFovPort *arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrFovPort *)jarg2; 
  {
    size_t ii;
    ovrFovPort *b = (ovrFovPort *) arg1->DefaultEyeFov;
    for (ii = 0; ii < (size_t)ovrEye_Count; ii++) b[ii] = *((ovrFovPort *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrHmdDesc_DefaultEyeFov_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrFovPort *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrFovPort *)(ovrFovPort *) ((arg1)->DefaultEyeFov);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_MaxEyeFov_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrFovPort *arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrFovPort *)jarg2; 
  {
    size_t ii;
    ovrFovPort *b = (ovrFovPort *) arg1->MaxEyeFov;
    for (ii = 0; ii < (size_t)ovrEye_Count; ii++) b[ii] = *((ovrFovPort *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrHmdDesc_MaxEyeFov_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrFovPort *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrFovPort *)(ovrFovPort *) ((arg1)->MaxEyeFov);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_EyeRenderOrder_set(void * jarg1, void * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrEyeType *arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (ovrEyeType *)jarg2; 
  {
    size_t ii;
    ovrEyeType *b = (ovrEyeType *) arg1->EyeRenderOrder;
    for (ii = 0; ii < (size_t)ovrEye_Count; ii++) b[ii] = *((ovrEyeType *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrHmdDesc_EyeRenderOrder_get(void * jarg1) {
  void * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  ovrEyeType *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (ovrEyeType *)(ovrEyeType *) ((arg1)->EyeRenderOrder);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_DisplayDeviceName_set(void * jarg1, char * jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->DisplayDeviceName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->DisplayDeviceName, (const char *)arg2);
    } else {
      arg1->DisplayDeviceName = 0;
    }
  }
}


SWIGEXPORT char * D_ovrHmdDesc_DisplayDeviceName_get(void * jarg1) {
  char * jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (char *) ((arg1)->DisplayDeviceName);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void D_ovrHmdDesc_DisplayId_set(void * jarg1, long jarg2) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  long arg2 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  arg2 = (long)jarg2;
  if (arg1) (arg1)->DisplayId = arg2;
}


SWIGEXPORT long D_ovrHmdDesc_DisplayId_get(void * jarg1) {
  long jresult ;
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  long result;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  result = (long) ((arg1)->DisplayId);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrHmdDesc() {
  void * jresult ;
  struct ovrHmdDesc_ *result = 0 ;
  
  result = (struct ovrHmdDesc_ *)calloc(1, sizeof(struct ovrHmdDesc_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrHmdDesc(void * jarg1) {
  struct ovrHmdDesc_ *arg1 = (struct ovrHmdDesc_ *) 0 ;
  
  arg1 = (struct ovrHmdDesc_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrSensorState_Predicted_set(void * jarg1, void * jarg2) {
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  ovrPoseStatef *arg2 = (ovrPoseStatef *) 0 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  arg2 = (ovrPoseStatef *)jarg2;
  if (arg1) (arg1)->Predicted = *arg2;
}


SWIGEXPORT void * D_ovrSensorState_Predicted_get(void * jarg1) {
  void * jresult ;
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  ovrPoseStatef *result = 0 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  result = (ovrPoseStatef *)& ((arg1)->Predicted);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrSensorState_Recorded_set(void * jarg1, void * jarg2) {
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  ovrPoseStatef *arg2 = (ovrPoseStatef *) 0 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  arg2 = (ovrPoseStatef *)jarg2;
  if (arg1) (arg1)->Recorded = *arg2;
}


SWIGEXPORT void * D_ovrSensorState_Recorded_get(void * jarg1) {
  void * jresult ;
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  ovrPoseStatef *result = 0 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  result = (ovrPoseStatef *)& ((arg1)->Recorded);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrSensorState_Temperature_set(void * jarg1, float jarg2) {
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->Temperature = arg2;
}


SWIGEXPORT float D_ovrSensorState_Temperature_get(void * jarg1) {
  float jresult ;
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  float result;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  result = (float) ((arg1)->Temperature);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrSensorState_StatusFlags_set(void * jarg1, unsigned int jarg2) {
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->StatusFlags = arg2;
}


SWIGEXPORT unsigned int D_ovrSensorState_StatusFlags_get(void * jarg1) {
  unsigned int jresult ;
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  unsigned int result;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  result = (unsigned int) ((arg1)->StatusFlags);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrSensorState() {
  void * jresult ;
  struct ovrSensorState_ *result = 0 ;
  
  result = (struct ovrSensorState_ *)calloc(1, sizeof(struct ovrSensorState_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrSensorState(void * jarg1) {
  struct ovrSensorState_ *arg1 = (struct ovrSensorState_ *) 0 ;
  
  arg1 = (struct ovrSensorState_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrSensorDesc_VendorId_set(void * jarg1, short jarg2) {
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  short arg2 ;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  arg2 = (short)jarg2;
  if (arg1) (arg1)->VendorId = arg2;
}


SWIGEXPORT short D_ovrSensorDesc_VendorId_get(void * jarg1) {
  short jresult ;
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  short result;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  result = (short) ((arg1)->VendorId);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrSensorDesc_ProductId_set(void * jarg1, short jarg2) {
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  short arg2 ;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  arg2 = (short)jarg2;
  if (arg1) (arg1)->ProductId = arg2;
}


SWIGEXPORT short D_ovrSensorDesc_ProductId_get(void * jarg1) {
  short jresult ;
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  short result;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  result = (short) ((arg1)->ProductId);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrSensorDesc_SerialNumber_set(void * jarg1, char * jarg2) {
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  char *arg2 ;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  arg2 = (char *)jarg2; 
  {
    if(arg2) {
      strncpy((char*)arg1->SerialNumber, (const char *)arg2, 24-1);
      arg1->SerialNumber[24-1] = 0;
    } else {
      arg1->SerialNumber[0] = 0;
    }
  }
}


SWIGEXPORT char * D_ovrSensorDesc_SerialNumber_get(void * jarg1) {
  char * jresult ;
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  result = (char *)(char *) ((arg1)->SerialNumber);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * D_new_ovrSensorDesc() {
  void * jresult ;
  struct ovrSensorDesc_ *result = 0 ;
  
  result = (struct ovrSensorDesc_ *)calloc(1, sizeof(struct ovrSensorDesc_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrSensorDesc(void * jarg1) {
  struct ovrSensorDesc_ *arg1 = (struct ovrSensorDesc_ *) 0 ;
  
  arg1 = (struct ovrSensorDesc_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrFrameTiming_DeltaSeconds_set(void * jarg1, float jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->DeltaSeconds = arg2;
}


SWIGEXPORT float D_ovrFrameTiming_DeltaSeconds_get(void * jarg1) {
  float jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  float result;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (float) ((arg1)->DeltaSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFrameTiming_ThisFrameSeconds_set(void * jarg1, double jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (double)jarg2;
  if (arg1) (arg1)->ThisFrameSeconds = arg2;
}


SWIGEXPORT double D_ovrFrameTiming_ThisFrameSeconds_get(void * jarg1) {
  double jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double result;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (double) ((arg1)->ThisFrameSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFrameTiming_TimewarpPointSeconds_set(void * jarg1, double jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (double)jarg2;
  if (arg1) (arg1)->TimewarpPointSeconds = arg2;
}


SWIGEXPORT double D_ovrFrameTiming_TimewarpPointSeconds_get(void * jarg1) {
  double jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double result;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (double) ((arg1)->TimewarpPointSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFrameTiming_NextFrameSeconds_set(void * jarg1, double jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (double)jarg2;
  if (arg1) (arg1)->NextFrameSeconds = arg2;
}


SWIGEXPORT double D_ovrFrameTiming_NextFrameSeconds_get(void * jarg1) {
  double jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double result;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (double) ((arg1)->NextFrameSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFrameTiming_ScanoutMidpointSeconds_set(void * jarg1, double jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (double)jarg2;
  if (arg1) (arg1)->ScanoutMidpointSeconds = arg2;
}


SWIGEXPORT double D_ovrFrameTiming_ScanoutMidpointSeconds_get(void * jarg1) {
  double jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double result;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (double) ((arg1)->ScanoutMidpointSeconds);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrFrameTiming_EyeScanoutSeconds_set(void * jarg1, void * jarg2) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double *arg2 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  arg2 = (double *)jarg2; 
  {
    size_t ii;
    double *b = (double *) arg1->EyeScanoutSeconds;
    for (ii = 0; ii < (size_t)2; ii++) b[ii] = *((double *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrFrameTiming_EyeScanoutSeconds_get(void * jarg1) {
  void * jresult ;
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  double *result = 0 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  result = (double *)(double *) ((arg1)->EyeScanoutSeconds);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * D_new_ovrFrameTiming() {
  void * jresult ;
  struct ovrFrameTiming_ *result = 0 ;
  
  result = (struct ovrFrameTiming_ *)calloc(1, sizeof(struct ovrFrameTiming_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrFrameTiming(void * jarg1) {
  struct ovrFrameTiming_ *arg1 = (struct ovrFrameTiming_ *) 0 ;
  
  arg1 = (struct ovrFrameTiming_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrEyeDesc_Eye_set(void * jarg1, int jarg2) {
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrEyeType arg2 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  if (arg1) (arg1)->Eye = arg2;
}


SWIGEXPORT int D_ovrEyeDesc_Eye_get(void * jarg1) {
  int jresult ;
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrEyeType result;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  result = (ovrEyeType) ((arg1)->Eye);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrEyeDesc_TextureSize_set(void * jarg1, void * jarg2) {
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrSizei *arg2 = (ovrSizei *) 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  arg2 = (ovrSizei *)jarg2;
  if (arg1) (arg1)->TextureSize = *arg2;
}


SWIGEXPORT void * D_ovrEyeDesc_TextureSize_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrSizei *result = 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  result = (ovrSizei *)& ((arg1)->TextureSize);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrEyeDesc_RenderViewport_set(void * jarg1, void * jarg2) {
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrRecti *arg2 = (ovrRecti *) 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  arg2 = (ovrRecti *)jarg2;
  if (arg1) (arg1)->RenderViewport = *arg2;
}


SWIGEXPORT void * D_ovrEyeDesc_RenderViewport_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrRecti *result = 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  result = (ovrRecti *)& ((arg1)->RenderViewport);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrEyeDesc_Fov_set(void * jarg1, void * jarg2) {
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrFovPort *arg2 = (ovrFovPort *) 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  arg2 = (ovrFovPort *)jarg2;
  if (arg1) (arg1)->Fov = *arg2;
}


SWIGEXPORT void * D_ovrEyeDesc_Fov_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  ovrFovPort *result = 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  result = (ovrFovPort *)& ((arg1)->Fov);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrEyeDesc() {
  void * jresult ;
  struct ovrEyeDesc_ *result = 0 ;
  
  result = (struct ovrEyeDesc_ *)calloc(1, sizeof(struct ovrEyeDesc_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrEyeDesc(void * jarg1) {
  struct ovrEyeDesc_ *arg1 = (struct ovrEyeDesc_ *) 0 ;
  
  arg1 = (struct ovrEyeDesc_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrEyeRenderDesc_Desc_set(void * jarg1, void * jarg2) {
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrEyeDesc *arg2 = (ovrEyeDesc *) 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  arg2 = (ovrEyeDesc *)jarg2;
  if (arg1) (arg1)->Desc = *arg2;
}


SWIGEXPORT void * D_ovrEyeRenderDesc_Desc_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrEyeDesc *result = 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  result = (ovrEyeDesc *)& ((arg1)->Desc);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrEyeRenderDesc_DistortedViewport_set(void * jarg1, void * jarg2) {
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrRecti *arg2 = (ovrRecti *) 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  arg2 = (ovrRecti *)jarg2;
  if (arg1) (arg1)->DistortedViewport = *arg2;
}


SWIGEXPORT void * D_ovrEyeRenderDesc_DistortedViewport_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrRecti *result = 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  result = (ovrRecti *)& ((arg1)->DistortedViewport);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrEyeRenderDesc_PixelsPerTanAngleAtCenter_set(void * jarg1, void * jarg2) {
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrVector2f *arg2 = (ovrVector2f *) 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  arg2 = (ovrVector2f *)jarg2;
  if (arg1) (arg1)->PixelsPerTanAngleAtCenter = *arg2;
}


SWIGEXPORT void * D_ovrEyeRenderDesc_PixelsPerTanAngleAtCenter_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrVector2f *result = 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  result = (ovrVector2f *)& ((arg1)->PixelsPerTanAngleAtCenter);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrEyeRenderDesc_ViewAdjust_set(void * jarg1, void * jarg2) {
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrVector3f *arg2 = (ovrVector3f *) 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  arg2 = (ovrVector3f *)jarg2;
  if (arg1) (arg1)->ViewAdjust = *arg2;
}


SWIGEXPORT void * D_ovrEyeRenderDesc_ViewAdjust_get(void * jarg1) {
  void * jresult ;
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  ovrVector3f *result = 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  result = (ovrVector3f *)& ((arg1)->ViewAdjust);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrEyeRenderDesc() {
  void * jresult ;
  struct ovrEyeRenderDesc_ *result = 0 ;
  
  result = (struct ovrEyeRenderDesc_ *)calloc(1, sizeof(struct ovrEyeRenderDesc_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrEyeRenderDesc(void * jarg1) {
  struct ovrEyeRenderDesc_ *arg1 = (struct ovrEyeRenderDesc_ *) 0 ;
  
  arg1 = (struct ovrEyeRenderDesc_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrRenderAPIConfigHeader_API_set(void * jarg1, int jarg2) {
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  ovrRenderAPIType arg2 ;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  arg2 = (ovrRenderAPIType)jarg2; 
  if (arg1) (arg1)->API = arg2;
}


SWIGEXPORT int D_ovrRenderAPIConfigHeader_API_get(void * jarg1) {
  int jresult ;
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  ovrRenderAPIType result;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  result = (ovrRenderAPIType) ((arg1)->API);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrRenderAPIConfigHeader_RTSize_set(void * jarg1, void * jarg2) {
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  ovrSizei *arg2 = (ovrSizei *) 0 ;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  arg2 = (ovrSizei *)jarg2;
  if (arg1) (arg1)->RTSize = *arg2;
}


SWIGEXPORT void * D_ovrRenderAPIConfigHeader_RTSize_get(void * jarg1) {
  void * jresult ;
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  ovrSizei *result = 0 ;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  result = (ovrSizei *)& ((arg1)->RTSize);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrRenderAPIConfigHeader_Multisample_set(void * jarg1, int jarg2) {
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  int arg2 ;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  arg2 = (int)jarg2;
  if (arg1) (arg1)->Multisample = arg2;
}


SWIGEXPORT int D_ovrRenderAPIConfigHeader_Multisample_get(void * jarg1) {
  int jresult ;
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  int result;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  result = (int) ((arg1)->Multisample);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrRenderAPIConfigHeader() {
  void * jresult ;
  struct ovrRenderAPIConfigHeader_ *result = 0 ;
  
  result = (struct ovrRenderAPIConfigHeader_ *)calloc(1, sizeof(struct ovrRenderAPIConfigHeader_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrRenderAPIConfigHeader(void * jarg1) {
  struct ovrRenderAPIConfigHeader_ *arg1 = (struct ovrRenderAPIConfigHeader_ *) 0 ;
  
  arg1 = (struct ovrRenderAPIConfigHeader_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrRenderAPIConfig_Header_set(void * jarg1, void * jarg2) {
  struct ovrRenderAPIConfig_ *arg1 = (struct ovrRenderAPIConfig_ *) 0 ;
  ovrRenderAPIConfigHeader *arg2 = (ovrRenderAPIConfigHeader *) 0 ;
  
  arg1 = (struct ovrRenderAPIConfig_ *)jarg1;
  arg2 = (ovrRenderAPIConfigHeader *)jarg2;
  if (arg1) (arg1)->Header = *arg2;
}


SWIGEXPORT void * D_ovrRenderAPIConfig_Header_get(void * jarg1) {
  void * jresult ;
  struct ovrRenderAPIConfig_ *arg1 = (struct ovrRenderAPIConfig_ *) 0 ;
  ovrRenderAPIConfigHeader *result = 0 ;
  
  arg1 = (struct ovrRenderAPIConfig_ *)jarg1;
  result = (ovrRenderAPIConfigHeader *)& ((arg1)->Header);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrRenderAPIConfig_PlatformData_set(void * jarg1, void * jarg2) {
  struct ovrRenderAPIConfig_ *arg1 = (struct ovrRenderAPIConfig_ *) 0 ;
  uintptr_t *arg2 ;
  
  arg1 = (struct ovrRenderAPIConfig_ *)jarg1;
  arg2 = (uintptr_t *)jarg2; 
  {
    size_t ii;
    uintptr_t *b = (uintptr_t *) arg1->PlatformData;
    for (ii = 0; ii < (size_t)8; ii++) b[ii] = *((uintptr_t *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrRenderAPIConfig_PlatformData_get(void * jarg1) {
  void * jresult ;
  struct ovrRenderAPIConfig_ *arg1 = (struct ovrRenderAPIConfig_ *) 0 ;
  uintptr_t *result = 0 ;
  
  arg1 = (struct ovrRenderAPIConfig_ *)jarg1;
  result = (uintptr_t *)(uintptr_t *) ((arg1)->PlatformData);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * D_new_ovrRenderAPIConfig() {
  void * jresult ;
  struct ovrRenderAPIConfig_ *result = 0 ;
  
  result = (struct ovrRenderAPIConfig_ *)calloc(1, sizeof(struct ovrRenderAPIConfig_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrRenderAPIConfig(void * jarg1) {
  struct ovrRenderAPIConfig_ *arg1 = (struct ovrRenderAPIConfig_ *) 0 ;
  
  arg1 = (struct ovrRenderAPIConfig_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrTextureHeader_API_set(void * jarg1, int jarg2) {
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrRenderAPIType arg2 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  arg2 = (ovrRenderAPIType)jarg2; 
  if (arg1) (arg1)->API = arg2;
}


SWIGEXPORT int D_ovrTextureHeader_API_get(void * jarg1) {
  int jresult ;
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrRenderAPIType result;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  result = (ovrRenderAPIType) ((arg1)->API);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void D_ovrTextureHeader_TextureSize_set(void * jarg1, void * jarg2) {
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrSizei *arg2 = (ovrSizei *) 0 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  arg2 = (ovrSizei *)jarg2;
  if (arg1) (arg1)->TextureSize = *arg2;
}


SWIGEXPORT void * D_ovrTextureHeader_TextureSize_get(void * jarg1) {
  void * jresult ;
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrSizei *result = 0 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  result = (ovrSizei *)& ((arg1)->TextureSize);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrTextureHeader_RenderViewport_set(void * jarg1, void * jarg2) {
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrRecti *arg2 = (ovrRecti *) 0 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  arg2 = (ovrRecti *)jarg2;
  if (arg1) (arg1)->RenderViewport = *arg2;
}


SWIGEXPORT void * D_ovrTextureHeader_RenderViewport_get(void * jarg1) {
  void * jresult ;
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  ovrRecti *result = 0 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  result = (ovrRecti *)& ((arg1)->RenderViewport);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrTextureHeader() {
  void * jresult ;
  struct ovrTextureHeader_ *result = 0 ;
  
  result = (struct ovrTextureHeader_ *)calloc(1, sizeof(struct ovrTextureHeader_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrTextureHeader(void * jarg1) {
  struct ovrTextureHeader_ *arg1 = (struct ovrTextureHeader_ *) 0 ;
  
  arg1 = (struct ovrTextureHeader_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrTexture_Header_set(void * jarg1, void * jarg2) {
  struct ovrTexture_ *arg1 = (struct ovrTexture_ *) 0 ;
  ovrTextureHeader *arg2 = (ovrTextureHeader *) 0 ;
  
  arg1 = (struct ovrTexture_ *)jarg1;
  arg2 = (ovrTextureHeader *)jarg2;
  if (arg1) (arg1)->Header = *arg2;
}


SWIGEXPORT void * D_ovrTexture_Header_get(void * jarg1) {
  void * jresult ;
  struct ovrTexture_ *arg1 = (struct ovrTexture_ *) 0 ;
  ovrTextureHeader *result = 0 ;
  
  arg1 = (struct ovrTexture_ *)jarg1;
  result = (ovrTextureHeader *)& ((arg1)->Header);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrTexture_PlatformData_set(void * jarg1, void * jarg2) {
  struct ovrTexture_ *arg1 = (struct ovrTexture_ *) 0 ;
  uintptr_t *arg2 ;
  
  arg1 = (struct ovrTexture_ *)jarg1;
  arg2 = (uintptr_t *)jarg2; 
  {
    size_t ii;
    uintptr_t *b = (uintptr_t *) arg1->PlatformData;
    for (ii = 0; ii < (size_t)8; ii++) b[ii] = *((uintptr_t *) arg2 + ii);
  }
}


SWIGEXPORT void * D_ovrTexture_PlatformData_get(void * jarg1) {
  void * jresult ;
  struct ovrTexture_ *arg1 = (struct ovrTexture_ *) 0 ;
  uintptr_t *result = 0 ;
  
  arg1 = (struct ovrTexture_ *)jarg1;
  result = (uintptr_t *)(uintptr_t *) ((arg1)->PlatformData);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * D_new_ovrTexture() {
  void * jresult ;
  struct ovrTexture_ *result = 0 ;
  
  result = (struct ovrTexture_ *)calloc(1, sizeof(struct ovrTexture_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrTexture(void * jarg1) {
  struct ovrTexture_ *arg1 = (struct ovrTexture_ *) 0 ;
  
  arg1 = (struct ovrTexture_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT char D_ovr_Initialize() {
  char jresult ;
  ovrBool result;
  
  result = (ovrBool)ovr_Initialize();
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovr_Shutdown() {
  ovr_Shutdown();
}


SWIGEXPORT int D_ovrHmd_Detect() {
  int jresult ;
  int result;
  
  result = (int)ovrHmd_Detect();
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_ovrHmd_Create(int jarg1) {
  void * jresult ;
  int arg1 ;
  ovrHmd result;
  
  arg1 = (int)jarg1;
  result = (ovrHmd)ovrHmd_Create(arg1);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrHmd_Destroy(void * jarg1) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  ovrHmd_Destroy(arg1);
}


SWIGEXPORT void * D_ovrHmd_CreateDebug(int jarg1) {
  void * jresult ;
  ovrHmdType arg1 ;
  ovrHmd result;
  
  arg1 = (ovrHmdType)jarg1; 
  result = (ovrHmd)ovrHmd_CreateDebug(arg1);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT char * D_ovrHmd_GetLastError(void * jarg1) {
  char * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *result = 0 ;
  
  arg1 = (ovrHmd)jarg1;
  result = (char *)ovrHmd_GetLastError(arg1);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char D_ovrHmd_StartSensor(void * jarg1, unsigned int jarg2, unsigned int jarg3) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned int)jarg2;
  arg3 = (unsigned int)jarg3;
  result = (ovrBool)ovrHmd_StartSensor(arg1,arg2,arg3);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrHmd_StopSensor(void * jarg1) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  ovrHmd_StopSensor(arg1);
}


SWIGEXPORT void D_ovrHmd_ResetSensor(void * jarg1) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  ovrHmd_ResetSensor(arg1);
}


SWIGEXPORT void * D_ovrHmd_GetSensorState(void * jarg1, double jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  double arg2 ;
  ovrSensorState result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (double)jarg2;
  result = ovrHmd_GetSensorState(arg1,arg2);
  {
    ovrSensorState * resultptr = (ovrSensorState *) malloc(sizeof(ovrSensorState));
    memmove(resultptr, &result, sizeof(ovrSensorState));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT char D_ovrHmd_GetSensorDesc(void * jarg1, void * jarg2) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrSensorDesc *arg2 = (ovrSensorDesc *) 0 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrSensorDesc *)jarg2;
  result = (ovrBool)ovrHmd_GetSensorDesc(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrHmd_GetDesc(void * jarg1, void * jarg2) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrHmdDesc *arg2 = (ovrHmdDesc *) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrHmdDesc *)jarg2;
  ovrHmd_GetDesc(arg1,arg2);
}


SWIGEXPORT void * D_ovrHmd_GetFovTextureSize(void * jarg1, int jarg2, void * jarg3, float jarg4) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeType arg2 ;
  ovrFovPort arg3 ;
  float arg4 ;
  ovrFovPort *argp3 ;
  ovrSizei result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  argp3 = (ovrFovPort *)jarg3;
  if (!argp3) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrFovPort");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (float)jarg4;
  result = ovrHmd_GetFovTextureSize(arg1,arg2,arg3,arg4);
  {
    ovrSizei * resultptr = (ovrSizei *) malloc(sizeof(ovrSizei));
    memmove(resultptr, &result, sizeof(ovrSizei));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT char D_ovrHmd_ConfigureRendering(void * jarg1, void * jarg2, unsigned int jarg3, unsigned int jarg4, void * jarg5, void * jarg6) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrRenderAPIConfig *arg2 = (ovrRenderAPIConfig *) 0 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  ovrEyeDesc *arg5 ;
  ovrEyeRenderDesc *arg6 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrRenderAPIConfig *)jarg2;
  arg3 = (unsigned int)jarg3;
  arg4 = (unsigned int)jarg4;
  arg5 = (ovrEyeDesc *)jarg5; 
  arg6 = (ovrEyeRenderDesc *)jarg6; 
  result = (ovrBool)ovrHmd_ConfigureRendering(arg1,(struct ovrRenderAPIConfig_ const *)arg2,arg3,arg4,(struct ovrEyeDesc_ const (*))arg5,arg6);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_ovrHmd_BeginFrame(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned int arg2 ;
  ovrFrameTiming result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned int)jarg2;
  result = ovrHmd_BeginFrame(arg1,arg2);
  {
    ovrFrameTiming * resultptr = (ovrFrameTiming *) malloc(sizeof(ovrFrameTiming));
    memmove(resultptr, &result, sizeof(ovrFrameTiming));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrHmd_EndFrame(void * jarg1) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  ovrHmd_EndFrame(arg1);
}


SWIGEXPORT void * D_ovrHmd_BeginEyeRender(void * jarg1, int jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeType arg2 ;
  ovrPosef result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  result = ovrHmd_BeginEyeRender(arg1,arg2);
  {
    ovrPosef * resultptr = (ovrPosef *) malloc(sizeof(ovrPosef));
    memmove(resultptr, &result, sizeof(ovrPosef));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrHmd_EndEyeRender(void * jarg1, int jarg2, void * jarg3, void * jarg4) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeType arg2 ;
  ovrPosef arg3 ;
  ovrTexture *arg4 = (ovrTexture *) 0 ;
  ovrPosef *argp3 ;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  argp3 = (ovrPosef *)jarg3;
  if (!argp3) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrPosef");
    return ;
  }
  arg3 = *argp3; 
  arg4 = (ovrTexture *)jarg4;
  ovrHmd_EndEyeRender(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void * D_ovrHmd_GetRenderDesc(void * jarg1, void * jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeDesc arg2 ;
  ovrEyeDesc *argp2 ;
  ovrEyeRenderDesc result;
  
  arg1 = (ovrHmd)jarg1;
  argp2 = (ovrEyeDesc *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrEyeDesc");
    return 0;
  }
  arg2 = *argp2; 
  result = ovrHmd_GetRenderDesc(arg1,arg2);
  {
    ovrEyeRenderDesc * resultptr = (ovrEyeRenderDesc *) malloc(sizeof(ovrEyeRenderDesc));
    memmove(resultptr, &result, sizeof(ovrEyeRenderDesc));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_Pos_set(void * jarg1, void * jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *arg2 = (ovrVector2f *) 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (ovrVector2f *)jarg2;
  if (arg1) (arg1)->Pos = *arg2;
}


SWIGEXPORT void * D_ovrDistortionVertex_Pos_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *result = 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (ovrVector2f *)& ((arg1)->Pos);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_TimeWarpFactor_set(void * jarg1, float jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->TimeWarpFactor = arg2;
}


SWIGEXPORT float D_ovrDistortionVertex_TimeWarpFactor_get(void * jarg1) {
  float jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  float result;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (float) ((arg1)->TimeWarpFactor);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_VignetteFactor_set(void * jarg1, float jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  float arg2 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (float)jarg2;
  if (arg1) (arg1)->VignetteFactor = arg2;
}


SWIGEXPORT float D_ovrDistortionVertex_VignetteFactor_get(void * jarg1) {
  float jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  float result;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (float) ((arg1)->VignetteFactor);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_TexR_set(void * jarg1, void * jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *arg2 = (ovrVector2f *) 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (ovrVector2f *)jarg2;
  if (arg1) (arg1)->TexR = *arg2;
}


SWIGEXPORT void * D_ovrDistortionVertex_TexR_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *result = 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (ovrVector2f *)& ((arg1)->TexR);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_TexG_set(void * jarg1, void * jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *arg2 = (ovrVector2f *) 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (ovrVector2f *)jarg2;
  if (arg1) (arg1)->TexG = *arg2;
}


SWIGEXPORT void * D_ovrDistortionVertex_TexG_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *result = 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (ovrVector2f *)& ((arg1)->TexG);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionVertex_TexB_set(void * jarg1, void * jarg2) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *arg2 = (ovrVector2f *) 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  arg2 = (ovrVector2f *)jarg2;
  if (arg1) (arg1)->TexB = *arg2;
}


SWIGEXPORT void * D_ovrDistortionVertex_TexB_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  ovrVector2f *result = 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  result = (ovrVector2f *)& ((arg1)->TexB);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrDistortionVertex() {
  void * jresult ;
  struct ovrDistortionVertex_ *result = 0 ;
  
  result = (struct ovrDistortionVertex_ *)calloc(1, sizeof(struct ovrDistortionVertex_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrDistortionVertex(void * jarg1) {
  struct ovrDistortionVertex_ *arg1 = (struct ovrDistortionVertex_ *) 0 ;
  
  arg1 = (struct ovrDistortionVertex_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrDistortionMesh_pVertexData_set(void * jarg1, void * jarg2) {
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  ovrDistortionVertex *arg2 = (ovrDistortionVertex *) 0 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  arg2 = (ovrDistortionVertex *)jarg2;
  if (arg1) (arg1)->pVertexData = arg2;
}


SWIGEXPORT void * D_ovrDistortionMesh_pVertexData_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  ovrDistortionVertex *result = 0 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  result = (ovrDistortionVertex *) ((arg1)->pVertexData);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionMesh_pIndexData_set(void * jarg1, void * jarg2) {
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned short *arg2 = (unsigned short *) 0 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  arg2 = (unsigned short *)jarg2;
  if (arg1) (arg1)->pIndexData = arg2;
}


SWIGEXPORT void * D_ovrDistortionMesh_pIndexData_get(void * jarg1) {
  void * jresult ;
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned short *result = 0 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  result = (unsigned short *) ((arg1)->pIndexData);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionMesh_VertexCount_set(void * jarg1, unsigned int jarg2) {
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->VertexCount = arg2;
}


SWIGEXPORT unsigned int D_ovrDistortionMesh_VertexCount_get(void * jarg1) {
  unsigned int jresult ;
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned int result;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  result = (unsigned int) ((arg1)->VertexCount);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrDistortionMesh_IndexCount_set(void * jarg1, unsigned int jarg2) {
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned int arg2 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  arg2 = (unsigned int)jarg2;
  if (arg1) (arg1)->IndexCount = arg2;
}


SWIGEXPORT unsigned int D_ovrDistortionMesh_IndexCount_get(void * jarg1) {
  unsigned int jresult ;
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  unsigned int result;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  result = (unsigned int) ((arg1)->IndexCount);
  jresult = result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrDistortionMesh() {
  void * jresult ;
  struct ovrDistortionMesh_ *result = 0 ;
  
  result = (struct ovrDistortionMesh_ *)calloc(1, sizeof(struct ovrDistortionMesh_));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrDistortionMesh(void * jarg1) {
  struct ovrDistortionMesh_ *arg1 = (struct ovrDistortionMesh_ *) 0 ;
  
  arg1 = (struct ovrDistortionMesh_ *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT char D_ovrHmd_CreateDistortionMesh(void * jarg1, void * jarg2, unsigned int jarg3, void * jarg4, void * jarg5) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeDesc arg2 ;
  unsigned int arg3 ;
  ovrVector2f *arg4 ;
  ovrDistortionMesh *arg5 = (ovrDistortionMesh *) 0 ;
  ovrEyeDesc *argp2 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  argp2 = (ovrEyeDesc *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrEyeDesc");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (unsigned int)jarg3;
  arg4 = (ovrVector2f *)jarg4; 
  arg5 = (ovrDistortionMesh *)jarg5;
  result = (ovrBool)ovrHmd_CreateDistortionMesh(arg1,arg2,arg3,arg4,arg5);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrHmd_DestroyDistortionMesh(void * jarg1) {
  ovrDistortionMesh *arg1 = (ovrDistortionMesh *) 0 ;
  
  arg1 = (ovrDistortionMesh *)jarg1;
  ovrHmd_DestroyDistortionMesh(arg1);
}


SWIGEXPORT void D_ovrHmd_GetRenderScaleAndOffset(void * jarg1, void * jarg2, unsigned int jarg3, void * jarg4) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeDesc arg2 ;
  unsigned int arg3 ;
  ovrVector2f *arg4 ;
  ovrEyeDesc *argp2 ;
  
  arg1 = (ovrHmd)jarg1;
  argp2 = (ovrEyeDesc *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrEyeDesc");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (unsigned int)jarg3;
  arg4 = (ovrVector2f *)jarg4; 
  ovrHmd_GetRenderScaleAndOffset(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void * D_ovrHmd_GetFrameTiming(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned int arg2 ;
  ovrFrameTiming result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned int)jarg2;
  result = ovrHmd_GetFrameTiming(arg1,arg2);
  {
    ovrFrameTiming * resultptr = (ovrFrameTiming *) malloc(sizeof(ovrFrameTiming));
    memmove(resultptr, &result, sizeof(ovrFrameTiming));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * D_ovrHmd_BeginFrameTiming(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned int arg2 ;
  ovrFrameTiming result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned int)jarg2;
  result = ovrHmd_BeginFrameTiming(arg1,arg2);
  {
    ovrFrameTiming * resultptr = (ovrFrameTiming *) malloc(sizeof(ovrFrameTiming));
    memmove(resultptr, &result, sizeof(ovrFrameTiming));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrHmd_EndFrameTiming(void * jarg1) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  
  arg1 = (ovrHmd)jarg1;
  ovrHmd_EndFrameTiming(arg1);
}


SWIGEXPORT void D_ovrHmd_ResetFrameTiming(void * jarg1, unsigned int jarg2, char jarg3) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned int arg2 ;
  ovrBool arg3 ;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned int)jarg2;
  arg3 = (ovrBool)jarg3;
  ovrHmd_ResetFrameTiming(arg1,arg2,arg3);
}


SWIGEXPORT void * D_ovrHmd_GetEyePose(void * jarg1, int jarg2) {
  void * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeType arg2 ;
  ovrPosef result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  result = ovrHmd_GetEyePose(arg1,arg2);
  {
    ovrPosef * resultptr = (ovrPosef *) malloc(sizeof(ovrPosef));
    memmove(resultptr, &result, sizeof(ovrPosef));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrHmd_GetEyeTimewarpMatrices(void * jarg1, int jarg2, void * jarg3, void * jarg4) {
  ovrHmd arg1 = (ovrHmd) 0 ;
  ovrEyeType arg2 ;
  ovrPosef arg3 ;
  ovrMatrix4f *arg4 ;
  ovrPosef *argp3 ;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (ovrEyeType)jarg2; 
  argp3 = (ovrPosef *)jarg3;
  if (!argp3) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrPosef");
    return ;
  }
  arg3 = *argp3; 
  arg4 = (ovrMatrix4f *)jarg4; 
  ovrHmd_GetEyeTimewarpMatrices(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void * D_ovrMatrix4f_Projection(void * jarg1, float jarg2, float jarg3, char jarg4) {
  void * jresult ;
  ovrFovPort arg1 ;
  float arg2 ;
  float arg3 ;
  ovrBool arg4 ;
  ovrFovPort *argp1 ;
  ovrMatrix4f result;
  
  argp1 = (ovrFovPort *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrFovPort");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (float)jarg2;
  arg3 = (float)jarg3;
  arg4 = (ovrBool)jarg4;
  result = ovrMatrix4f_Projection(arg1,arg2,arg3,arg4);
  {
    ovrMatrix4f * resultptr = (ovrMatrix4f *) malloc(sizeof(ovrMatrix4f));
    memmove(resultptr, &result, sizeof(ovrMatrix4f));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * D_ovrMatrix4f_OrthoSubProjection(void * jarg1, void * jarg2, float jarg3, float jarg4) {
  void * jresult ;
  ovrMatrix4f arg1 ;
  ovrVector2f arg2 ;
  float arg3 ;
  float arg4 ;
  ovrMatrix4f *argp1 ;
  ovrVector2f *argp2 ;
  ovrMatrix4f result;
  
  argp1 = (ovrMatrix4f *)jarg1;
  if (!argp1) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrMatrix4f");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (ovrVector2f *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null ovrVector2f");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (float)jarg3;
  arg4 = (float)jarg4;
  result = ovrMatrix4f_OrthoSubProjection(arg1,arg2,arg3,arg4);
  {
    ovrMatrix4f * resultptr = (ovrMatrix4f *) malloc(sizeof(ovrMatrix4f));
    memmove(resultptr, &result, sizeof(ovrMatrix4f));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT double D_ovr_GetTimeInSeconds() {
  double jresult ;
  double result;
  
  result = (double)ovr_GetTimeInSeconds();
  jresult = result;
  return jresult;
}


SWIGEXPORT double D_ovr_WaitTillTime(double jarg1) {
  double jresult ;
  double arg1 ;
  double result;
  
  arg1 = (double)jarg1;
  result = (double)ovr_WaitTillTime(arg1);
  jresult = result;
  return jresult;
}


SWIGEXPORT char D_ovrHmd_ProcessLatencyTest(void * jarg1, void * jarg2) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  unsigned char *arg2 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (unsigned char *)jarg2; 
  result = (ovrBool)ovrHmd_ProcessLatencyTest(arg1,arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT char * D_ovrHmd_GetLatencyTestResult(void * jarg1) {
  char * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *result = 0 ;
  
  arg1 = (ovrHmd)jarg1;
  result = (char *)ovrHmd_GetLatencyTestResult(arg1);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT double D_ovrHmd_GetMeasuredLatencyTest2(void * jarg1) {
  double jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  double result;
  
  arg1 = (ovrHmd)jarg1;
  result = (double)ovrHmd_GetMeasuredLatencyTest2(arg1);
  jresult = result;
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_USER_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "User";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_NAME_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "Name";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_GENDER_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "Gender";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_PLAYER_HEIGHT_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "PlayerHeight";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_EYE_HEIGHT_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "EyeHeight";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_IPD_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "IPD";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_NECK_TO_EYE_HORIZONTAL_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "NeckEyeHori";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_KEY_NECK_TO_EYE_VERTICAL_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "NeckEyeVert";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * D_OVR_DEFAULT_GENDER_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *) "Male";
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT double D_OVR_DEFAULT_PLAYER_HEIGHT_get() {
  double jresult ;
  double result;
  
  result = (double) 1.778;
  jresult = result;
  return jresult;
}


SWIGEXPORT double D_OVR_DEFAULT_EYE_HEIGHT_get() {
  double jresult ;
  double result;
  
  result = (double) 1.675;
  jresult = result;
  return jresult;
}


SWIGEXPORT double D_OVR_DEFAULT_IPD_get() {
  double jresult ;
  double result;
  
  result = (double) 0.064;
  jresult = result;
  return jresult;
}


SWIGEXPORT double D_OVR_DEFAULT_NECK_TO_EYE_HORIZONTAL_get() {
  double jresult ;
  double result;
  
  result = (double) 0.12;
  jresult = result;
  return jresult;
}


SWIGEXPORT double D_OVR_DEFAULT_NECK_TO_EYE_VERTICAL_get() {
  double jresult ;
  double result;
  
  result = (double) 0.12;
  jresult = result;
  return jresult;
}


SWIGEXPORT float D_ovrHmd_GetFloat(void * jarg1, char * jarg2, float jarg3) {
  float jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  float arg3 ;
  float result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  arg3 = (float)jarg3;
  result = (float)ovrHmd_GetFloat(arg1,(char const *)arg2,arg3);
  jresult = result;
  return jresult;
}


SWIGEXPORT char D_ovrHmd_SetFloat(void * jarg1, char * jarg2, float jarg3) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  float arg3 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  arg3 = (float)jarg3;
  result = (ovrBool)ovrHmd_SetFloat(arg1,(char const *)arg2,arg3);
  jresult = result;
  return jresult;
}


SWIGEXPORT unsigned int D_ovrHmd_GetFloatArray(void * jarg1, char * jarg2, void * jarg3, unsigned int jarg4) {
  unsigned int jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  float *arg3 ;
  unsigned int arg4 ;
  unsigned int result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (unsigned int)jarg4;
  result = (unsigned int)ovrHmd_GetFloatArray(arg1,(char const *)arg2,arg3,arg4);
  jresult = result;
  return jresult;
}


SWIGEXPORT char D_ovrHmd_SetFloatArray(void * jarg1, char * jarg2, void * jarg3, unsigned int jarg4) {
  char jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  float *arg3 ;
  unsigned int arg4 ;
  ovrBool result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (unsigned int)jarg4;
  result = (ovrBool)ovrHmd_SetFloatArray(arg1,(char const *)arg2,arg3,arg4);
  jresult = result;
  return jresult;
}


SWIGEXPORT char * D_ovrHmd_GetString(void * jarg1, char * jarg2, char * jarg3) {
  char * jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = (char *)ovrHmd_GetString(arg1,(char const *)arg2,(char const *)arg3);
  jresult = SWIG_d_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned int D_ovrHmd_GetArraySize(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  ovrHmd arg1 = (ovrHmd) 0 ;
  char *arg2 = (char *) 0 ;
  unsigned int result;
  
  arg1 = (ovrHmd)jarg1;
  arg2 = (char *)jarg2; 
  result = (unsigned int)ovrHmd_GetArraySize(arg1,(char const *)arg2);
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_ovrGLConfigData_Header_set(void * jarg1, void * jarg2) {
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  ovrRenderAPIConfigHeader *arg2 = (ovrRenderAPIConfigHeader *) 0 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  arg2 = (ovrRenderAPIConfigHeader *)jarg2;
  if (arg1) (arg1)->Header = *arg2;
}


SWIGEXPORT void * D_ovrGLConfigData_Header_get(void * jarg1) {
  void * jresult ;
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  ovrRenderAPIConfigHeader *result = 0 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  result = (ovrRenderAPIConfigHeader *)& ((arg1)->Header);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrGLConfigData_Window_set(void * jarg1, void * jarg2) {
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HWND arg2 ;
  HWND *argp2 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  argp2 = (HWND *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null HWND");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Window = arg2;
}


SWIGEXPORT void * D_ovrGLConfigData_Window_get(void * jarg1) {
  void * jresult ;
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HWND result;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  result =  ((arg1)->Window);
  {
    HWND * resultptr = (HWND *) malloc(sizeof(HWND));
    memmove(resultptr, &result, sizeof(HWND));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrGLConfigData_WglContext_set(void * jarg1, void * jarg2) {
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HGLRC arg2 ;
  HGLRC *argp2 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  argp2 = (HGLRC *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null HGLRC");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->WglContext = arg2;
}


SWIGEXPORT void * D_ovrGLConfigData_WglContext_get(void * jarg1) {
  void * jresult ;
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HGLRC result;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  result =  ((arg1)->WglContext);
  {
    HGLRC * resultptr = (HGLRC *) malloc(sizeof(HGLRC));
    memmove(resultptr, &result, sizeof(HGLRC));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void D_ovrGLConfigData_GdiDc_set(void * jarg1, void * jarg2) {
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HDC arg2 ;
  HDC *argp2 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  argp2 = (HDC *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null HDC");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->GdiDc = arg2;
}


SWIGEXPORT void * D_ovrGLConfigData_GdiDc_get(void * jarg1) {
  void * jresult ;
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  HDC result;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  result =  ((arg1)->GdiDc);
  {
    HDC * resultptr = (HDC *) malloc(sizeof(HDC));
    memmove(resultptr, &result, sizeof(HDC));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * D_new_ovrGLConfigData() {
  void * jresult ;
  struct ovrGLConfigData_s *result = 0 ;
  
  result = (struct ovrGLConfigData_s *)calloc(1, sizeof(struct ovrGLConfigData_s));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrGLConfigData(void * jarg1) {
  struct ovrGLConfigData_s *arg1 = (struct ovrGLConfigData_s *) 0 ;
  
  arg1 = (struct ovrGLConfigData_s *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrGLConfig_Config_set(void * jarg1, void * jarg2) {
  union ovrGLConfig *arg1 = (union ovrGLConfig *) 0 ;
  ovrRenderAPIConfig *arg2 = (ovrRenderAPIConfig *) 0 ;
  
  arg1 = (union ovrGLConfig *)jarg1;
  arg2 = (ovrRenderAPIConfig *)jarg2;
  if (arg1) (arg1)->Config = *arg2;
}


SWIGEXPORT void * D_ovrGLConfig_Config_get(void * jarg1) {
  void * jresult ;
  union ovrGLConfig *arg1 = (union ovrGLConfig *) 0 ;
  ovrRenderAPIConfig *result = 0 ;
  
  arg1 = (union ovrGLConfig *)jarg1;
  result = (ovrRenderAPIConfig *)& ((arg1)->Config);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrGLConfig_OGL_set(void * jarg1, void * jarg2) {
  union ovrGLConfig *arg1 = (union ovrGLConfig *) 0 ;
  ovrGLConfigData *arg2 = (ovrGLConfigData *) 0 ;
  
  arg1 = (union ovrGLConfig *)jarg1;
  arg2 = (ovrGLConfigData *)jarg2;
  if (arg1) (arg1)->OGL = *arg2;
}


SWIGEXPORT void * D_ovrGLConfig_OGL_get(void * jarg1) {
  void * jresult ;
  union ovrGLConfig *arg1 = (union ovrGLConfig *) 0 ;
  ovrGLConfigData *result = 0 ;
  
  arg1 = (union ovrGLConfig *)jarg1;
  result = (ovrGLConfigData *)& ((arg1)->OGL);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrGLConfig() {
  void * jresult ;
  union ovrGLConfig *result = 0 ;
  
  result = (union ovrGLConfig *)calloc(1, sizeof(union ovrGLConfig));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrGLConfig(void * jarg1) {
  union ovrGLConfig *arg1 = (union ovrGLConfig *) 0 ;
  
  arg1 = (union ovrGLConfig *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrGLTextureData_Header_set(void * jarg1, void * jarg2) {
  struct ovrGLTextureData_s *arg1 = (struct ovrGLTextureData_s *) 0 ;
  ovrTextureHeader *arg2 = (ovrTextureHeader *) 0 ;
  
  arg1 = (struct ovrGLTextureData_s *)jarg1;
  arg2 = (ovrTextureHeader *)jarg2;
  if (arg1) (arg1)->Header = *arg2;
}


SWIGEXPORT void * D_ovrGLTextureData_Header_get(void * jarg1) {
  void * jresult ;
  struct ovrGLTextureData_s *arg1 = (struct ovrGLTextureData_s *) 0 ;
  ovrTextureHeader *result = 0 ;
  
  arg1 = (struct ovrGLTextureData_s *)jarg1;
  result = (ovrTextureHeader *)& ((arg1)->Header);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrGLTextureData_TexId_set(void * jarg1, void * jarg2) {
  struct ovrGLTextureData_s *arg1 = (struct ovrGLTextureData_s *) 0 ;
  GLuint arg2 ;
  GLuint *argp2 ;
  
  arg1 = (struct ovrGLTextureData_s *)jarg1;
  argp2 = (GLuint *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null GLuint");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->TexId = arg2;
}


SWIGEXPORT void * D_ovrGLTextureData_TexId_get(void * jarg1) {
  void * jresult ;
  struct ovrGLTextureData_s *arg1 = (struct ovrGLTextureData_s *) 0 ;
  GLuint result;
  
  arg1 = (struct ovrGLTextureData_s *)jarg1;
  result =  ((arg1)->TexId);
  {
    GLuint * resultptr = (GLuint *) malloc(sizeof(GLuint));
    memmove(resultptr, &result, sizeof(GLuint));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * D_new_ovrGLTextureData() {
  void * jresult ;
  struct ovrGLTextureData_s *result = 0 ;
  
  result = (struct ovrGLTextureData_s *)calloc(1, sizeof(struct ovrGLTextureData_s));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrGLTextureData(void * jarg1) {
  struct ovrGLTextureData_s *arg1 = (struct ovrGLTextureData_s *) 0 ;
  
  arg1 = (struct ovrGLTextureData_s *)jarg1;
  free((char *) arg1);
}


SWIGEXPORT void D_ovrGLTexture_Texture_set(void * jarg1, void * jarg2) {
  union ovrGLTexture_s *arg1 = (union ovrGLTexture_s *) 0 ;
  ovrTexture *arg2 = (ovrTexture *) 0 ;
  
  arg1 = (union ovrGLTexture_s *)jarg1;
  arg2 = (ovrTexture *)jarg2;
  if (arg1) (arg1)->Texture = *arg2;
}


SWIGEXPORT void * D_ovrGLTexture_Texture_get(void * jarg1) {
  void * jresult ;
  union ovrGLTexture_s *arg1 = (union ovrGLTexture_s *) 0 ;
  ovrTexture *result = 0 ;
  
  arg1 = (union ovrGLTexture_s *)jarg1;
  result = (ovrTexture *)& ((arg1)->Texture);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_ovrGLTexture_OGL_set(void * jarg1, void * jarg2) {
  union ovrGLTexture_s *arg1 = (union ovrGLTexture_s *) 0 ;
  ovrGLTextureData *arg2 = (ovrGLTextureData *) 0 ;
  
  arg1 = (union ovrGLTexture_s *)jarg1;
  arg2 = (ovrGLTextureData *)jarg2;
  if (arg1) (arg1)->OGL = *arg2;
}


SWIGEXPORT void * D_ovrGLTexture_OGL_get(void * jarg1) {
  void * jresult ;
  union ovrGLTexture_s *arg1 = (union ovrGLTexture_s *) 0 ;
  ovrGLTextureData *result = 0 ;
  
  arg1 = (union ovrGLTexture_s *)jarg1;
  result = (ovrGLTextureData *)& ((arg1)->OGL);
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void * D_new_ovrGLTexture() {
  void * jresult ;
  union ovrGLTexture_s *result = 0 ;
  
  result = (union ovrGLTexture_s *)calloc(1, sizeof(union ovrGLTexture_s));
  jresult = (void *)result;
  return jresult;
}


SWIGEXPORT void D_delete_ovrGLTexture(void * jarg1) {
  union ovrGLTexture_s *arg1 = (union ovrGLTexture_s *) 0 ;
  
  arg1 = (union ovrGLTexture_s *)jarg1;
  free((char *) arg1);
}


#ifdef __cplusplus
}
#endif

